### ISSUE TITLE
sttdef.h not found

### ISSUE THREAD

**Issue by arcanosam** [Shopify/javy#103]
It's seems that the header **__struct_iovec.h**  not find the header **stddef.h**

When I search for it I find it in two folders:

./crates/quickjs-wasm-sys/wasi-sdk/lib/clang/11.0.0/include/stddef.h
./crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot/include/c++/v1/stddef.h

I'm on Fedora 35.

**backtrace of build javy executable (I replace my path for ~)**:

export RUST_BACKTRACE=1 && make
cd crates/core \
                        && cargo build --release --target=wasm32-wasi \
                        && cd -
   Compiling quickjs-wasm-sys v0.1.0 (/javy/crates/quickjs-wasm-sys)
The following warnings were emitted during compilation:

warning: quickjs/quickjs.c:1689:12: warning: implicit declaration of function 'malloc_usable_size' is invalid in C99 [-Wimplicit-function-declaration]
warning:     return malloc_usable_size(ptr);
warning:            ^
warning: quickjs/quickjs.c:10742:30: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
warning:                 else if (d > INT64_MAX)
warning:                            ~ ^~~~~~~~~
warning: /javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot/include/stdint.h:46:21: note: expanded from macro 'INT64_MAX'
warning: #define INT64_MAX  (0x7fffffffffffffff)
warning:                     ^~~~~~~~~~~~~~~~~~
warning: 2 warnings generated.

error: failed to run custom build command for `quickjs-wasm-sys v0.1.0 (/javy/crates/quickjs-wasm-sys)`

Caused by:
  process didn't exit successfully: `/javy/target/release/build/quickjs-wasm-sys-19b8894d7843fb89/build-script-build` (exit status: 101)
  --- stdout
  TARGET = Some("wasm32-wasi")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  CC_wasm32-wasi = None
  CC_wasm32_wasi = None
  TARGET_CC = None
  CC = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang")
  CFLAGS_wasm32-wasi = None
  CFLAGS_wasm32_wasi = None
  TARGET_CFLAGS = None
  CFLAGS = Some("--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot")
  CRATE_CC_NO_DEFAULTS = None
  running: "/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-wasi" "--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot" "-Wchar-subscripts" "-Wno-array-bounds" "-Wno-missing-field-initializers" "-Wno-sign-compare" "-Wno-unused-parameter" "-Wundef" "-Wuninitialized" "-Wunused" "-Wwrite-strings" "-funsigned-char" "-Wno-implicit-fallthrough" "-Wno-enum-conversion" "-D_GNU_SOURCE" "-DCONFIG_VERSION=\"2021-03-27\"" "-DCONFIG_BIGNUM" "-o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/cutils.o" "-c" "quickjs/cutils.c"
  exit status: 0
  running: "/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-wasi" "--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot" "-Wchar-subscripts" "-Wno-array-bounds" "-Wno-missing-field-initializers" "-Wno-sign-compare" "-Wno-unused-parameter" "-Wundef" "-Wuninitialized" "-Wunused" "-Wwrite-strings" "-funsigned-char" "-Wno-implicit-fallthrough" "-Wno-enum-conversion" "-D_GNU_SOURCE" "-DCONFIG_VERSION=\"2021-03-27\"" "-DCONFIG_BIGNUM" "-o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/libbf.o" "-c" "quickjs/libbf.c"
  exit status: 0
  running: "/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-wasi" "--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot" "-Wchar-subscripts" "-Wno-array-bounds" "-Wno-missing-field-initializers" "-Wno-sign-compare" "-Wno-unused-parameter" "-Wundef" "-Wuninitialized" "-Wunused" "-Wwrite-strings" "-funsigned-char" "-Wno-implicit-fallthrough" "-Wno-enum-conversion" "-D_GNU_SOURCE" "-DCONFIG_VERSION=\"2021-03-27\"" "-DCONFIG_BIGNUM" "-o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/libregexp.o" "-c" "quickjs/libregexp.c"
  exit status: 0
  running: "/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-wasi" "--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot" "-Wchar-subscripts" "-Wno-array-bounds" "-Wno-missing-field-initializers" "-Wno-sign-compare" "-Wno-unused-parameter" "-Wundef" "-Wuninitialized" "-Wunused" "-Wwrite-strings" "-funsigned-char" "-Wno-implicit-fallthrough" "-Wno-enum-conversion" "-D_GNU_SOURCE" "-DCONFIG_VERSION=\"2021-03-27\"" "-DCONFIG_BIGNUM" "-o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/libunicode.o" "-c" "quickjs/libunicode.c"
  exit status: 0
  running: "/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-wasi" "--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot" "-Wchar-subscripts" "-Wno-array-bounds" "-Wno-missing-field-initializers" "-Wno-sign-compare" "-Wno-unused-parameter" "-Wundef" "-Wuninitialized" "-Wunused" "-Wwrite-strings" "-funsigned-char" "-Wno-implicit-fallthrough" "-Wno-enum-conversion" "-D_GNU_SOURCE" "-DCONFIG_VERSION=\"2021-03-27\"" "-DCONFIG_BIGNUM" "-o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/quickjs.o" "-c" "quickjs/quickjs.c"
  cargo:warning=quickjs/quickjs.c:1689:12: warning: implicit declaration of function 'malloc_usable_size' is invalid in C99 [-Wimplicit-function-declaration]
  cargo:warning=    return malloc_usable_size(ptr);
  cargo:warning=           ^
  cargo:warning=quickjs/quickjs.c:10742:30: warning: implicit conversion from 'long long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int-float-conversion]
  cargo:warning=                else if (d > INT64_MAX)
  cargo:warning=                           ~ ^~~~~~~~~
  cargo:warning=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot/include/stdint.h:46:21: note: expanded from macro 'INT64_MAX'
  cargo:warning=#define INT64_MAX  (0x7fffffffffffffff)
  cargo:warning=                    ^~~~~~~~~~~~~~~~~~
  cargo:warning=2 warnings generated.
  exit status: 0
  running: "/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-wasi" "--sysroot=/javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot" "-Wchar-subscripts" "-Wno-array-bounds" "-Wno-missing-field-initializers" "-Wno-sign-compare" "-Wno-unused-parameter" "-Wundef" "-Wuninitialized" "-Wunused" "-Wwrite-strings" "-funsigned-char" "-Wno-implicit-fallthrough" "-Wno-enum-conversion" "-D_GNU_SOURCE" "-DCONFIG_VERSION=\"2021-03-27\"" "-DCONFIG_BIGNUM" "-o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/extensions/value.o" "-c" "extensions/value.c"
  exit status: 0
  AR_wasm32-wasi = None
  AR_wasm32_wasi = None
  TARGET_AR = None
  AR = Some("/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/ar")
  running: "/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/ar" "cq" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/libquickjs.a" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/cutils.o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/libbf.o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/libregexp.o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/libunicode.o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/quickjs/quickjs.o" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/extensions/value.o"
  exit status: 0
  running: "/javy/crates/quickjs-wasm-sys/wasi-sdk/bin/ar" "s" "/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out/libquickjs.a"
  exit status: 0
  cargo:rustc-link-lib=static=quickjs
  cargo:rustc-link-search=native=/javy/target/wasm32-wasi/release/build/quickjs-wasm-sys-1c06c240ac5c4496/out

  --- stderr
  /javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot/include/__struct_iovec.h:5:10: fatal error: 'stddef.h' file not found
  /javy/crates/quickjs-wasm-sys/wasi-sdk/share/wasi-sysroot/include/__struct_iovec.h:5:10: fatal error: 'stddef.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', crates/quickjs-wasm-sys/build.rs:57:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
     2: core::result::unwrap_failed
               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
make: *** [Makefile:14: core] Error 101

**Comment by saulecabrera** [comment]
It seems that cargo can't locate the C dependencies (wasi-sdk). Did you run `make download-wasi-sdk` at the root?

**Comment by saulecabrera** [comment]
According to the latest comment it seems that this is related to clang; `make download-wasi-sdk` should download the clang toolchain and its dependencies. Feel free to open a different issue if it's not downloading the right dependencies for your platform.
